# Data Manupulation with Numpy
        -->Math
        -->Random
        -->Filtering
        -->Statistics
        -->Aggregation
        -->Saving Data
        

# Math

In [ ]:
import numpy as np

In [ ]:
#create one 2-D array using list
a = np.array([[1,2,3,4],[5,6,7,8]])
print("array:",a)
print("Shape:",a.shape)
print("dim:",a.ndim)

In [1]:
ar = a+2
ar

In [11]:
l = [1,2,3,4,5,6]
l * 2

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [12]:
a * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [13]:
a / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ]])

In [14]:
a % 2

array([[1, 0, 1, 0],
       [1, 0, 1, 0]], dtype=int32)

In [15]:
a//2

array([[0, 1, 1, 2],
       [2, 3, 3, 4]], dtype=int32)

In [18]:
print(np.power(a,2))
type(a)

[[ 1  4  9 16]
 [25 36 49 64]]


numpy.ndarray

In [20]:
str(a) # ndarray to str-----conversion of datatype is called type casting


'[[1 2 3 4]\n [5 6 7 8]]'

In [21]:
#square root of array
a ** 0.5

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [22]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [23]:
np.exp2(a)# exponentiation

array([[  2.,   4.,   8.,  16.],
       [ 32.,  64., 128., 256.]])

In [24]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154]])

In [25]:
np.log10(a)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999]])

In [26]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

# Random

In [27]:
import random

In [30]:
a1 = np.random.randint(10)
a1

5

In [32]:
a2 = np.random.randint(1,100,2) # low, high, shape
a2

array([24, 18])

In [34]:
a3 = np.random.randint(1,100,(3,3))
a3

array([[93, 90, 37],
       [46, 77, 72],
       [ 2, 38, 87]])

In [35]:
otp = np.random.randint(100000, 999999) # generating 6-digit otp
otp

234685

In [45]:
otp = np.random.randint(0,10,6)
list(otp)
int("".join(map(str,list(ar))))


460631

In [38]:
np.random.uniform()

0.8954584644769843

In [39]:
np.random.uniform(1,5)

1.2819253278344398

In [41]:
np.random.uniform(1,100,(5,5))

array([[33.57006477, 35.72503071, 69.60959595, 33.92032252, 49.09235578],
       [51.47771261, 64.35167693, 37.37047936, 66.40582871,  6.92355127],
       [44.51525974, 10.25830191, 31.58680193,  4.06558314,  8.90601838],
       [ 8.39712077, 78.53698807, 42.45369764, 47.43319738, 56.60817113],
       [10.25032354, 20.25913832, 28.13041272, 54.00771271, 22.79443511]])

In [42]:
name = ["varsha", "yokshi", "rishi", "sathvi"]
np.random.choice(name)

'sathvi'

In [48]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bit_generator',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',

# Filtering

In [50]:
# create 3,3 2-D array
ag = np.random.randint(-100,100,[3,3])
print(ag.ndim)
print(ag.shape)
print(ag)

2
(3, 3)
[[ 60 -64  10]
 [-65 -92 -53]
 [ 37  87 -28]]


In [51]:
ag > 0

array([[ True, False,  True],
       [False, False, False],
       [ True,  True, False]])

In [52]:
ag < 0

array([[False,  True, False],
       [ True,  True,  True],
       [False, False,  True]])

In [53]:
ag >= 50

array([[ True, False, False],
       [False, False, False],
       [False,  True, False]])

In [54]:
ag == 0

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [55]:
ag != 0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [56]:
ag2 = np.array([[1,2,3],[0,6,2],[7,8,4]])
ag2

array([[1, 2, 3],
       [0, 6, 2],
       [7, 8, 4]])

In [57]:
ag2 [ag2 > 3]

array([6, 7, 8, 4])

In [58]:
ag[ag != 0]

array([ 60, -64,  10, -65, -92, -53,  37,  87, -28])

In [59]:
ag[~(ag2 != 0)]

array([-65])

In [60]:
print(ag2)
ag2[~(ag2 != 0)]

[[1 2 3]
 [0 6 2]
 [7 8 4]]


array([0])

In [64]:
ag3 = np.array([[1,5,8],[np.nan,67,5],[52,np.nan,67]])# nan-> not a number
ag3

array([[ 1.,  5.,  8.],
       [nan, 67.,  5.],
       [52., nan, 67.]])

In [65]:
np.isnan(ag3)

array([[False, False, False],
       [ True, False, False],
       [False,  True, False]])

In [67]:
ag3[~(np.isnan(ag3))]

array([ 1.,  5.,  8., 67.,  5., 52., 67.])

In [68]:
ag3 * 3

array([[  3.,  15.,  24.],
       [ nan, 201.,  15.],
       [156.,  nan, 201.]])

In [71]:
ag3[1][0] = 123
ag3

array([[  1.,   5.,   8.],
       [123.,  67.,   5.],
       [ 52.,  nan,  67.]])

In [74]:
ag3[2:,1:2] = 13
ag3

array([[  1.,   5.,   8.],
       [123.,  67.,   5.],
       [ 52.,  13.,  67.]])

In [75]:
ag4 = np.array([1,0,32,5,48,35,7])
np.where(ag4 == 32) # returns index position

(array([2], dtype=int64),)

In [76]:
ag

array([[ 60, -64,  10],
       [-65, -92, -53],
       [ 37,  87, -28]])

In [77]:
ag>0

array([[ True, False,  True],
       [False, False, False],
       [ True,  True, False]])

In [78]:
np.any(a>0) #logical or operation ---> even one element in the array meets the given condition

True

In [79]:
np.all(a>0) #logical and operation ---> every element has to meet the given condition

True

In [80]:
ag2

array([[1, 2, 3],
       [0, 6, 2],
       [7, 8, 4]])

In [81]:
np.any(ag2>0)

True

In [82]:
np.all(ag2>0)

False

# Statistics / Analysis

In [83]:
ar

array([4, 6, 0, 6, 3, 1])

In [84]:
ar.min()

0

In [85]:
ar.max()

6

In [86]:
ar.mean()

3.3333333333333335

In [88]:
np.median(ar)

3.5

In [89]:
np.std(ar)

2.2852182001336816

In [90]:
np.var(ar)

5.222222222222222

In [94]:
ag2

array([[1, 2, 3],
       [0, 6, 2],
       [7, 8, 4]])

In [96]:
np.median(ag2, axis = 1) # axis=1--> column

array([2., 2., 7.])

In [97]:
np.median(ag2, axis = 0) # axis=0--> row

array([1., 6., 3.])

# Aggregation

In [98]:
ag2

array([[1, 2, 3],
       [0, 6, 2],
       [7, 8, 4]])

In [100]:
np.sum(ag2) #returns overall summation

33

In [101]:
np.sum(ag2, axis = 0)

array([ 8, 16,  9])

In [102]:
np.sum(ag2, axis = 1)

array([ 6,  8, 19])

In [108]:
# concatenation
print(ag2)
np.concatenate([ag2,ag2]) # it concate in rows as default

[[1 2 3]
 [0 6 2]
 [7 8 4]]


array([[1, 2, 3],
       [0, 6, 2],
       [7, 8, 4],
       [1, 2, 3],
       [0, 6, 2],
       [7, 8, 4]])

In [110]:
print(ag2)
data = np.concatenate([ag2,ag2],axis= 1)
data

[[1 2 3]
 [0 6 2]
 [7 8 4]]


array([[1, 2, 3, 1, 2, 3],
       [0, 6, 2, 0, 6, 2],
       [7, 8, 4, 7, 8, 4]])

# Saving Data

In [115]:
np.save("array",data)

In [114]:
np.save("data_array.npy",data)

In [116]:
np.load("data_array.npy")

array([[1, 2, 3, 1, 2, 3],
       [0, 6, 2, 0, 6, 2],
       [7, 8, 4, 7, 8, 4]])

# Task
# Create this array by using numpy methods

11111
11001
10101
10011
11111

In [122]:
fg=np.ones([5,5], dtype = int)
fg[1,2:4]=0
fg[2,3]=0
fg[3,1:3]=0
fg[2,1]=0
print(fg)


[[1 1 1 1 1]
 [1 1 0 0 1]
 [1 0 1 0 1]
 [1 0 0 1 1]
 [1 1 1 1 1]]


In [132]:
task = np.eye(5,dtype = int)
task

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [133]:
task[[0,-1]] = 1
task

array([[1, 1, 1, 1, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 1, 1, 1, 1]])

In [134]:
task[:, 0:1] = 1
task[:, -1] = 1
task

array([[1, 1, 1, 1, 1],
       [1, 1, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1]])