**Numpy:

In [11]:
# Importing numpy library
import numpy as np

Creating array:

In [17]:
a1 = np.array([1.0,2,3,4,'m']) #1-D array
a1

array(['1.0', '2', '3', '4', 'm'], dtype='<U32')

In [18]:
a1.dtype #checking the datatype of the array elements

dtype('<U32')

In [20]:
a1 = np.append(a1,['f', 15])
a1

array(['1.0', '2', '3', '4', 'm', 'f', '15', 'f', '15'], dtype='<U32')

In [22]:
a = np.arange(5,11) #to create arrays within a range
a

array([ 5,  6,  7,  8,  9, 10])

In [23]:
a = np.arange(5, 11, 2) # range with step value
a

array([5, 7, 9])

In [24]:
a.nbytes # to ckeck memory space occupied

12

In [25]:
a.itemsize # for individual element size

4

In [27]:
len(a) # to check length of the array

3

In [30]:
np.linspace(1,20,5) #Dividing the given range with equal difference between each element

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [32]:
np.full(10," Python") #repeating the same value for defined count

array([' Python', ' Python', ' Python', ' Python', ' Python', ' Python',
       ' Python', ' Python', ' Python', ' Python'], dtype='<U7')

In [35]:
np.ones(10) #for having ones in array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.ones(10, dtype = int) 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [37]:
np.zeros(10) # for getting seroes in the array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
### 1-D array:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [40]:
### 2-D array: -----> combination of more 1-D arrays
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
### 3-D array: Combination of more 2-D arrays
a3 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,8,7,6],[4,3,2,1]]])
a3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 8, 7, 6],
        [4, 3, 2, 1]]])

In [43]:
a1.ndim

1

In [45]:
a2.ndim

2

In [46]:
a3.ndim

3

In [51]:
## Multi dimensional array
am = np.array([1,2,3,4], ndmin = 10)
am

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [54]:
am1 = np.array([[1,2,3,4],[5,6,7,8]], ndmin = 10)
am1

array([[[[[[[[[[1, 2, 3, 4],
               [5, 6, 7, 8]]]]]]]]]])

# Accessing elements from the array

In [55]:
# Accessing elements from 1-D array:
a1

array([1, 2, 3, 4])

In [56]:
a1[-1] # for last  value

4

In [57]:
a1[2]

3

In [58]:
a1[1:3] # for accessing a range of values using slicing

array([2, 3])

In [60]:
### accessing elements from 2-D array:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
a2[0]

array([1, 2, 3, 4])

In [62]:
a2[1]

array([5, 6, 7, 8])

In [63]:
a2[0,2] # 0 index and 2nd index with in that

3

In [64]:
a2[1,-1]

8

In [66]:
a2[:,-1]

array([4, 8])

In [68]:
a2[:,1:3]

array([[2, 3],
       [6, 7]])

In [75]:
a2[:,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [76]:
a = np.array([[1,2,2],[3,4,5],[5,6,7]])
a

array([[1, 2, 2],
       [3, 4, 5],
       [5, 6, 7]])

In [77]:
a[1:,1:] #Row slicing

array([[4, 5],
       [6, 7]])

In [78]:
### accessing eleemnts from 3-D array:
a3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 8, 7, 6],
        [4, 3, 2, 1]]])

In [79]:
a3[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
a3[1]

array([[9, 8, 7, 6],
       [4, 3, 2, 1]])

In [81]:
a3[1,0]

array([9, 8, 7, 6])

In [82]:
a3[0,0,2:]

array([3, 4])

In [83]:
a3[1,1,2:]

array([2, 1])

In [85]:
a3[:,:,2:]

array([[[3, 4],
        [7, 8]],

       [[7, 6],
        [2, 1]]])

In [87]:
### shape of the array:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
a.shape

(2, 4)

In [89]:
a1

array([1, 2, 3, 4])

In [90]:
a1.shape

(4,)

In [91]:
a3.shape

(2, 2, 4)

In [92]:
### Reshape of the array:
## note : total length of the array should be even
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [95]:
a.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
a.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [100]:
a.reshape(2,3,-1)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])